### ISSUE TITLE
Don't touch line breaks (or add options for it)

### ISSUE THREAD

**Issue by philippevk** [maxogden/standard-format#113]
I think the formatter should not add or remove line breaks anywhere since the standard doesn't say anything about this. Alternatively you could provide an option for this.

Great work btw!

**Comment by bcomnes** [comment]
Originally we were only aiming to fix standard violations, but esformatter doesn't have enough hooks to make that possible... so at the moment, you will always get some formatting, and unfortunately it will sometimes touch non violating line breaks.  If [you spot a rule](https://github.com/maxogden/standard-format/blob/master/rc/esformatter.json) that we can relax or disable, please feel free to bring it up as a sugestion, otherwise work is ongoing to improve the flexibility of formatting.  

As for options, a major part of standard's purpose is to minimize options, so any improvements along these lines would need to be flexible enough always be active.

**Comment by philippevk** [comment]
I'm leaving for the weekend but from what I see it should be possible by setting most of the line break rules to - 1. I'll try something when I get back and keep you posted. Thanks for the fast response!

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
