### ISSUE TITLE
Adding more indentation when returning object in ES6

### ISSUE THREAD

**Issue by sospedra** [maxogden/standard-format#127]
Giving the following example:

```
return array.map(el => ({
  inc: el.val + 1,
  dec: el.val - 1
}))
```

It adds 4 spaces of indentation instead of 2

**Comment by bcomnes** [comment]
Writing some tests for this.  Looks like arrow functions have some hooks in esformatter now so I might actually be able to fix this potentially.

**Comment by edravis** [comment]
Let me know if you need some help.

**Comment by bcomnes** [comment]
The issue seems to come from the the indentation on ObjectExpression's.
```js
return array.map(el => ({
    inc: el.val + 1,
    dec: el.val - 1
 }})
```

Where the rule is primarily used to make objects look like this:

```js
{
  foo: bar
}
```

Because its nested inside of an arrow function inside of the the map , its adding two layers of indentation.

I don't see an easy way to fix this at the moment.  Any thoughts on the matter?

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
